config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :notes, only: [:show, :new, :create, :update] do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :text, allow_nil: false, length: { maximum: 2000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def search
  end

  def show
    @note = Note.find_by(uuid: params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to action: :show, id: @note.reload.uuid
    else
      render :new
    end
  end

  def update
    @note = Note.find_by(uuid: params[:id])

    if @note&.view_count
      @note.update!(view_count: @note.view_count - 1)

      if @note.view_count.zero?
        @note.destroy
      end
    end
  end

  private

  def note_params
    return @note_params if @note_params

    @note_params = params.expect(note: [:text])

    if params.delete(:delete_on_view)
      @note_params[:view_count] = 1
    end

    @note_params
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cryptonotes</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- favicon generator -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-bar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>

      <%= link_to t(".name"), "https://github.com/zfletch/cryptonotes-rails", class: "navbar-brand", target: "_blank" %>
    </div>

    <div class="collapse navbar-collapse" id="nav-bar">
      <ul class="nav navbar-nav">
        <li class=<%= current_page?(root_path) ? "active" : "" %>>
          <%= link_to t('.home'), root_path %>
        </li>
        <li class=<%= current_page?(new_note_path) ? "active" : "" %>>
          <%= link_to t('.new'), new_note_path %>
        </li>
        <li class="hidden-sm hidden-md hidden-lg <%= current_page?(search_notes_path) ? "active" : ""%>">
          <%= link_to t('.find'), search_notes_path %>
        </li>
      </ul>

      <form class="navbar-form navbar-left hidden-xs" role="search">
        <div class="form-group">
          <input type="text" class="form-control" id="key" placeholder="Key">
        </div>
        <button class="btn btn-default" id="go"><%= t(".find") %></button>
      </form>
    </div>
  </div>
</nav>

<script>
(function () {
  var path = '/notes/';

  var gobutton = $("#go");
  var key = $("#key");

  gobutton.on("click", function (e) {
    e.preventDefault();
    if (key.val() !== "") {
      window.location = path + encodeURIComponent(key.val());
    }
  });
})();
</script>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/notes/new.html.erb
<div id="error-container" class="alert alert-danger hidden" role="alert">
  <ul>
    <li id="text-too-long" class="hidden"><%= t(".text_too_long") %></li>
    <li id="missing-key" class="hidden"><%= t(".missing_key") %></li>
    <li id="missing-message" class="hidden"><%= t(".missing_message") %></li>
  </ul>
</div>

<div class="text-center">
  <h1><%= t(".title") %></h1>
</div>

<br>
<input class="form-control" id="password" placeholder="<%= t(".key") %>">
<br>
<textarea rows="10" class="form-control" id="plaintext" placeholder="<%= t(".message") %>" maxlength: "1000"></textarea>

<%= form_for @note, url: { action: :create } do |f| %>
  <%= f.text_field :text, maxlength: 2000, hidden: true %>
  <div class="checkbox-inline">
    <%= check_box_tag :delete_on_view, "1", true %>
    <%= f.label :delete_on_view, t(".deleteyn") %><br>
  </div>
  <br />
  <br />

  <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
<% end %>

<script>
(function () {

var plaintext = $("#plaintext");
var password = $("#password");
var noteText = $("#note_text");
var textTooLong = $("#text-too-long")
var missingKey = $("#missing-key")
var missingMessage = $("#missing-message");
var errorContainer = $("#error-container");
var form = $("#new_note");

var update = function () {
  var kval = password.val();
  var tval = plaintext.val();
  var errors = false;
  var text = sjcl.encrypt(kval, tval);

  errorContainer.addClass("hidden");
  textTooLong.addClass("hidden");
  missingKey.addClass("hidden");
  missingMessage.addClass("hidden");

  if (text.length > 2000) {
    textTooLong.removeClass("hidden");
    errors = true;
  }

  if (kval.trim() === '') {
    missingKey.removeClass("hidden");
    errors = true;
  }

  if (tval.trim() === '') {
    missingMessage.removeClass("hidden");
    errors = true;
  }

  if (errors) {
    errorContainer.removeClass("hidden");
    return false;
  } else {
    noteText.val(text);
  }
}

form.submit(update);

})();
</script>

app/views/notes/search.html.erb
<div class="text-center">
  <h1><%= t(".key") %></h1>

  <div class="form-group">
    <input type="text" class="form-control" id="find-key" placeholder="Key">
  </div>
  <button class="btn btn-primary btn-lg btn-block" id="find-go"><%= t(".find") %></button>
</div>

<script>
(function () {
  var path = '/notes/';

  var gobutton = $("#find-go");
  var key = $("#find-key");

  gobutton.on("click", function (e) {
    e.preventDefault();
    if (key.val() !== "") {
      window.location = path + encodeURIComponent(key.val());
    }
  });
})();
</script>

app/views/notes/show.html.erb
<% if @note %>

  <div class="text-center">
    <h1><%= t(".title") %></h1>

    <p class="lead">
      <%= t(".line1") %><br>
      <%= t(".line2") %><br>
    </p>

    <%= form_for @note, url: { action: :update, method: :patch } do |f| %>
      <%= f.hidden_field :id, value: @note.uuid %>
      <%= f.submit t(".submit"), class: "btn btn-primary btn-lg" %>
    <% end %>
    <br />

    <div class="container">
      <strong><%= t(".show_link") %> </strong>
      <%= link_to note_url(@note.uuid), note_path(@note.uuid), class: "note-link" %><br>
      <strong><%= t(".show_key") %> </strong>
      <span id="note-uuid">
        <%= @note.uuid %>
      </span>

      <% if @note.view_count && @note.view_count == 1 %>
        <h4><%= t(".delete") %></h4>
      <% end %>
    </div>
  </div>

<% else %>

  <div class="text-center">
    <h1><%= t(".no_note1") %></h1>
    <p class="lead">
    <%= t(".no_note2") %> <strong><%= params[:id] %></strong>.
    </p>
  </div>

<% end %>

app/views/notes/update.html.erb
<% if @note %>
  <div class="text-center">
    <h1><%= t(".title") %></h1>

    <% if @note.view_count && @note.view_count == 1 %>
      <h4><%= t(".delete1") %></h4>
    <% end %>

    <% if @note.view_count && @note.view_count == 0 %>
      <h4><%= t(".delete2") %></h4>
    <% end %>

  </div>

  <br>
  <input class="form-control" id="password" placeholder="<%= t(".key") %>">
  <br>

  <div id="encryptedtext" style="display: none;">
      <%= @note.text %>
  </div>

  <div id="plaintext" class="jumbotron lead"></div>

  <% if !@note.view_count || @note.view_count > 0 %>
    <strong><%= t(".show_link") %> </strong>
    <%= link_to note_url(@note.uuid), note_path(@note.uuid), class: "note-link" %><br>

    <strong><%= t(".show_key") %> </strong>
    <span id="note-uuid">
      <%= @note.uuid %>
    </span>
  <% end %>
<% else %>
  <div class="text-center">
    <h1><%= t(".no_note1") %></h1>
    <p class="lead">
    <%= t(".no_note2") %> <strong><%= params[:id] %></strong>.
    </p>
  </div>
<% end %>

<script>
(function () {

var encryptedtext = $("#encryptedtext");
var password = $("#password");
var plaintext = $("#plaintext");

var decrypt = function () {
  var text;
  var success = false;

  try {
    text = sjcl.decrypt(password.val(), encryptedtext.text());

    success = true;
  } catch (e) {
    plaintext.text('');
  }

  if (success && plaintext.text() !== text) {
    plaintext.text(text);
  }
}

setInterval(decrypt, 200);

})();

</script>

app/views/welcome/index.html.erb
<div class="text-center">
  <h1><%= t(".title") %></h1>
  <p class="lead">
    <%= t(".line1") %><br>
    <%= t(".line2") %><br>
  </p>

  <%= link_to t(".create"), new_note_path, class: "btn btn-primary btn-lg" %>
</div>